// <auto-generated />
using System;
using LaytonTemple.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTemple.Migrations
{
    [DbContext(typeof(LaytonTempleContext))]
    [Migration("20220321151455_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaytonTemple.Models.AvailableTimes", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeId");

                    b.ToTable("AvailableTimes");

                    b.HasData(
                        new
                        {
                            TimeId = 1,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 2,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 3,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 4,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 5,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 6,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 7,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 8,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 9,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 10,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 11,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 12,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 13,
                            Time = "9:00 PM"
                        });
                });

            modelBuilder.Entity("LaytonTemple.Models.Tour", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvailableTimesTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.HasIndex("AvailableTimesTimeId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("LaytonTemple.Models.Tour", b =>
                {
                    b.HasOne("LaytonTemple.Models.AvailableTimes", "AvailableTimes")
                        .WithMany()
                        .HasForeignKey("AvailableTimesTimeId");
                });
#pragma warning restore 612, 618
        }
    }
}
